In [1]:
import numpy as np
from sklearn.datasets import load_digits
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
def initializer(X, y):
    x = X.shape[0]
    fl = 3
    sl = y.shape[0]

    W1 = np.random.randn(fl,x)*0.01
    b1 = np.zeros((fl, 1))
    W2 = np.random.randn(sl,fl)*0.01
    b2 = np.zeros((sl,1))
    return {"size":[x,fl,sl],
            "params":[W1, b1, W2, b2]}

In [4]:
def ReLU_prime(z):
    result = (z >= 0).astype(int)

    return result

In [5]:
def ReLU(z):
    relu = np.maximum(0,z)
    return relu

In [6]:
def sigmoid(z):
    s = 1.0/(1+np.exp(-z))
    return s

In [7]:
mnist = load_digits()

In [28]:
from sklearn.model_selection import train_test_split
X,y = mnist.data, mnist.target
X , y.shape
y_o = (y == 0)

In [29]:
X_tr, y_tr, X_te, y_te = train_test_split(X,y_o,test_size=0.3, random_state=40)

In [10]:
X_tr.shape[0]

1257

In [35]:
def fprop(X, params):


    W1 = params[0]
    b1 = params[1]
    W2 = params[2]
    b2 = params[3]

    Z1 = np.dot(W1,X)+b1
    A1 = np.tanh(Z1)
    Z2 = np.dot(W2,A1)+b2
    A2 = sigmoid(Z2)

    

    #assert(A2.shape == (y.shape[], X.shape[1]))
    return  [Z1,A1,Z2,A2]

In [33]:
def cost(A2,y):
    m = y.shape[1]

    logprobs = ((y * np.log(A2))) + (((1-y) * np.log(1-A2)))
    print (logprobs)
    cost = (-1/m) * np.sum(logprobs)
    print (cost)
    cost = float(np.squeeze(cost))

    return cost

In [13]:
def backward_propagation(params, fprop, X, y):

    m = X.shape[1]
    
    W1 = params[0]
    b1 = params[1]
    W2 = params[2]
    b2 = params[3]

    Z1 = fprop[0]
    A1 = fprop[1]
    Z2 = fprop[2]
    A2 = fprop[3]

    dZ2 = A2 - y
    dW2 = (1/m) * np.dot(dZ2, A1.T)
    db2 = (1/m) * np.sum(dZ2, axis = 1, keepdims=True)
    dZ1 = np.dot(W2.T, dZ2) *  ()
    dW1 = (1/m) * np.dot(dZ1,X.T)
    db1 = (1/m) * np.sum(dZ1, axis = 1, keepdims=True)

    grads = {
        "dW1": dW1,
        "db1": db1,
        "dZ1": dZ1,
        "dW2": dW2,
        "db2": db2,
        "dZ2": dZ2,    
    }

    return grads

In [14]:
def update_params(params, grads, learning_rate = 1.2):
    W1 = params[0]
    b1 = params[1]
    W2 = params[2]
    b2 = params[3]

    dW1 = grads["dW1"]
    db1 = grads["db1"]
    dW2 = grads["dW2"]
    db2 = grads["db2"]

    W1 = W1 - learning_rate * dW1
    b1 = b1 - learning_rate * db1
    W2 = W2 - learning_rate * dW2
    b2 = b2 - learning_rate * db2

    params = [W1, b1, W2, b2]
    return params

In [17]:
def nn_model(X, y, num_iter = 3000, print_cost= True):
    np.random.seed(3)

    n_x , n_fl , n_y = initializer(X,y)["size"]

    parameters = initializer(X,y)["params"]

    W1 = parameters[0]
    b1 = parameters[1]
    W2 = parameters[2]
    b2 = parameters[3]

    for i in range(num_iter):

        print(i , "******")
        # fp
        Z1,A1,Z2,A2 = fprop(X, parameters)
        
        # cost
        costf = cost(A2, y)
        
        # bp
        grads = backward_propagation(parameters,[Z1,A1,Z2,A2],X,y)
        
        # gd
        parameters =  update_params(parameters, grads)


        # print cost
        if print_cost and i%1000 == 0:
            print ("Cost after iteration %i: %f" %(i, costf))
            
    return parameters

In [34]:
p = nn_model(X_tr,y_tr)
p

0 ******
[[-0.69314718 -0.69236406 -0.70936626 ... -0.7057199  -0.69314718
  -0.69203312]
 [-0.69314718 -0.69315785 -0.69164402 ... -0.66924497 -0.69314718
  -0.69316237]
 [-0.69314718 -0.69301548 -0.70511049 ... -0.79262157 -0.69314718
  -0.6929598 ]
 ...
 [-0.69314718 -0.69237506 -0.59196785 ... -0.73619354 -0.69314718
  -0.69204877]
 [-0.69314718 -0.69254101 -0.67849574 ... -1.75570637 -0.69314718
  -0.69228482]
 [-0.69314718 -0.69343265 -0.64046559 ... -0.67371358 -0.69314718
  -0.68868001]]
377.9190969725044
Cost after iteration 0: 377.919097
1 ******
[[-15.64080389         -inf          inf ...          inf         -inf
          -inf]
 [-11.93475828         -inf          nan ...          inf         -inf
          -inf]
 [-12.00872227         -inf          inf ...          inf         -inf
          -inf]
 ...
 [-14.49263367         -inf          inf ...         -inf         -inf
          -inf]
 [ -9.6954533          -inf         -inf ...          inf          inf
          -in

C:\Windows\Temp\ipykernel_1356\1489780696.py:4: RuntimeWarning: divide by zero encountered in log
  logprobs = ((y * np.log(A2))) + (((1-y) * np.log(1-A2)))
C:\Windows\Temp\ipykernel_1356\1489780696.py:4: RuntimeWarning: invalid value encountered in multiply
  logprobs = ((y * np.log(A2))) + (((1-y) * np.log(1-A2)))
D:\Programs\miniconda3\envs\homl3\lib\site-packages\numpy\core\fromnumeric.py:88: RuntimeWarning: invalid value encountered in reduce
  return ufunc.reduce(obj, axis, dtype, out, **passkwargs)


[[-inf -inf  inf ...  inf -inf -inf]
 [-inf -inf  nan ...  inf -inf -inf]
 [-inf -inf  inf ...  inf -inf -inf]
 ...
 [-inf -inf  inf ... -inf -inf -inf]
 [-inf -inf -inf ...  inf  inf -inf]
 [-inf -inf  inf ...  inf  inf  inf]]
nan
24 ******
[[-inf -inf  inf ...  inf -inf -inf]
 [-inf -inf  nan ...  inf -inf -inf]
 [-inf -inf  inf ...  inf -inf -inf]
 ...
 [-inf -inf  inf ... -inf -inf -inf]
 [-inf -inf -inf ...  inf  inf -inf]
 [-inf -inf  inf ...  inf  inf  inf]]
nan
25 ******
[[-inf -inf  inf ...  inf -inf -inf]
 [-inf -inf  nan ...  inf -inf -inf]
 [-inf -inf  inf ...  inf -inf -inf]
 ...
 [-inf -inf  inf ... -inf -inf -inf]
 [-inf -inf -inf ...  inf  inf -inf]
 [-inf -inf  inf ...  inf  inf  inf]]
nan
26 ******
[[-inf -inf  inf ...  inf -inf -inf]
 [-inf -inf  nan ...  inf -inf -inf]
 [-inf -inf  inf ...  inf -inf -inf]
 ...
 [-inf -inf  inf ... -inf -inf -inf]
 [-inf -inf -inf ...  inf  inf -inf]
 [-inf -inf  inf ...  inf  inf  inf]]
nan
27 ******
[[-inf -inf  inf ...  inf -inf -

[array([[nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan],
        [nan, nan, nan, ..., nan, nan, nan]]),
 array([[nan],
        [nan],
        [nan]]),
 array([[nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan],
        ...,
        [nan, nan, nan],
        [nan, nan, nan],
        [nan, nan, nan]]),
 array([[nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
        [nan],
      